-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.funcionario
(
    id serial NOT NULL,
    nome character varying(200) NOT NULL,
    matricula character varying(10) NOT NULL,
    supervisor_id integer,
    PRIMARY KEY (id),
    CONSTRAINT uk_matricula UNIQUE (matricula)
);

CREATE TABLE IF NOT EXISTS public.tipo_cargo
(
    id smallserial NOT NULL,
    descricao character varying(40) NOT NULL,
    tem_salario_minimo boolean NOT NULL DEFAULT False,
    PRIMARY KEY (id),
    CONSTRAINT uk_tipo_cargo_descricao UNIQUE (descricao)
);

CREATE TABLE IF NOT EXISTS public.maquina_costura
(
    id smallserial NOT NULL,
    fabricante_id smallint NOT NULL,
    localizacao_id smallint NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.tipo_maquina_costura
(
    id smallserial NOT NULL,
    descricao character varying(40) NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_tipo_maquina_costura_descricao UNIQUE (descricao)
);

CREATE TABLE IF NOT EXISTS public.maquina_costura_tipo_maquina_costura
(
    maquina_costura_id smallint NOT NULL,
    tipo_maquina_costura_id smallint NOT NULL,
    PRIMARY KEY (maquina_costura_id, tipo_maquina_costura_id)
);

CREATE TABLE IF NOT EXISTS public.funcionario_tipo_cargo
(
    funcionario_id integer NOT NULL,
    tipo_cargo_id smallint NOT NULL,
    data_inicio date NOT NULL DEFAULT CURRENT_DATE,
    salario_minimo money,
    PRIMARY KEY (funcionario_id, tipo_cargo_id, data_inicio)
);

CREATE TABLE IF NOT EXISTS public.fabricante
(
    id smallserial NOT NULL,
    nome character varying(40) NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_nome UNIQUE (nome)
);

CREATE TABLE IF NOT EXISTS public.funcionario_tipo_maquina_costura
(
    funcionario_id integer NOT NULL,
    tipo_maquina_costura_id smallint NOT NULL,
    PRIMARY KEY (funcionario_id, tipo_maquina_costura_id)
);

CREATE TABLE IF NOT EXISTS public.peca_roupa
(
    id integer NOT NULL,
    funcionario_id integer NOT NULL,
    estilista_id smallint NOT NULL,
    maquina_costura_id smallint NOT NULL,
    data_inicio_prod time without time zone NOT NULL,
    data_final_prod time without time zone,
    preco_venda money NOT NULL,
    modelo character varying(20) NOT NULL,
    modelo_descricao character varying(200) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.estilista
(
    id smallserial NOT NULL,
    nome character varying(200) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.os_conserto
(
    id serial NOT NULL,
    funcionario_id integer NOT NULL,
    maquina_costura_id smallint NOT NULL,
    horario_inicio time without time zone DEFAULT NOW(),
    PRIMARY KEY (funcionario_id)
);

CREATE TABLE IF NOT EXISTS public.localizacao
(
    id smallserial NOT NULL,
    descricao character varying(40) NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_localizacao_descricao UNIQUE (descricao)
);

ALTER TABLE IF EXISTS public.funcionario
    ADD CONSTRAINT fk_supervisao FOREIGN KEY (supervisor_id)
    REFERENCES public.funcionario (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.maquina_costura
    ADD CONSTRAINT fk_fabricante FOREIGN KEY (fabricante_id)
    REFERENCES public.fabricante (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.maquina_costura
    ADD CONSTRAINT fk_localizacao FOREIGN KEY (localizacao_id)
    REFERENCES public.localizacao (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.maquina_costura_tipo_maquina_costura
    ADD CONSTRAINT fk_maquina_costura FOREIGN KEY (maquina_costura_id)
    REFERENCES public.maquina_costura (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.maquina_costura_tipo_maquina_costura
    ADD CONSTRAINT fk_tipo_maquina_costura_id FOREIGN KEY (tipo_maquina_costura_id)
    REFERENCES public.tipo_maquina_costura (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.funcionario_tipo_cargo
    ADD CONSTRAINT fk_funcionario FOREIGN KEY (funcionario_id)
    REFERENCES public.funcionario (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.funcionario_tipo_cargo
    ADD CONSTRAINT fk_tipo_cargo FOREIGN KEY (tipo_cargo_id)
    REFERENCES public.tipo_cargo (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.funcionario_tipo_maquina_costura
    ADD CONSTRAINT fk_funcionario FOREIGN KEY (funcionario_id)
    REFERENCES public.funcionario (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.funcionario_tipo_maquina_costura
    ADD CONSTRAINT fk_tipo_maquina_costura FOREIGN KEY (tipo_maquina_costura_id)
    REFERENCES public.tipo_maquina_costura (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.peca_roupa
    ADD CONSTRAINT fk_maquina_costura FOREIGN KEY (maquina_costura_id)
    REFERENCES public.maquina_costura (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.peca_roupa
    ADD CONSTRAINT fk_estilista FOREIGN KEY (estilista_id)
    REFERENCES public.estilista (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.peca_roupa
    ADD CONSTRAINT fk_funcionario FOREIGN KEY (funcionario_id)
    REFERENCES public.funcionario (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.os_conserto
    ADD CONSTRAINT fk_funcionario FOREIGN KEY (funcionario_id)
    REFERENCES public.funcionario (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.os_conserto
    ADD CONSTRAINT fk_maquina_costura FOREIGN KEY (maquina_costura_id)
    REFERENCES public.maquina_costura (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;
	
END;